{% set name = "itunespy" %}
{% set version = "1.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/itunespy-{{ version }}.tar.gz
  sha256: 528748baef17769b8d3c61badf0c031ac217c6387c481e825919641a557203a3

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - pycountry >=19.8
    - python >={{ python_min }}
    - requests >=2.8

test:
  imports:
    - itunespy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/spaceisstrange/itunespy
  summary: A simple library to fetch data from the iTunes Store API made for Python 3.X
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - HeavyTony2
